project:
  type: website
  output-dir: docs


website:
  title: "DataVizR2"
  # margin-footer: "Universidade Federal Fluminense Programa de formação de executivos Ciência de dados - 2024"

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Revisão
        href: revisao.qmd
      - text: Apresentação
        href: apresentacao.qmd
      - text: Dashboard
        href: dashboard.qmd
      - icon: github
        href: https://github.com/nextmarte/dataVizR2
        text: GitHub


format:
  html:
    theme:
      light: flatly
      dark: darkly

title: "DataVizR"

