project:
  type: website
  output-dir: docs


website:
  title: "DataVizR2"


  navbar:
    right:

      - icon: Home
        href: index.qmd      
      - text: Apresentação
        href: apresentacao.qmd
      - text: Dashboard
        href: dashboard.qmd
      - icon: github
        href: index.qmd
        text: GitHub


format:
  html:
    theme: cyborg

title: "DataVizR"

