project:
  type: website
  output-dir: docs


website:
  title: "DataVizR2"

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Revisão
        href: revisao.qmd
      - text: Apresentação
        href: apresentacao.qmd
      - text: Dashboard
        href: dashboard.qmd
      - icon: github
        href: https://github.com/nextmarte/dataVizR2
        text: GitHub


format:
  html:
    theme: cyborg

title: "DataVizR"

